### ISSUE TITLE
Maybe controller-bootstrap.js is unneeded

### ISSUE THREAD

**Issue by mindrones** [rachel-carvalho/chaplin-browserify-gulp#1]
Since you're using `.require(readControllers('./src/js/controllers'))` in `gulpfile.js` then maybe `src/js/controller-bootstrap.js` isn't needed?

Thanks a lot for publishing this solution!

**Comment by rachel-carvalho** [comment]
That is possible, I have to admit I'm not sure. I'm afk right now, but when
I get back I'll remove it and see if it's still necessary and report back.
Thanks for noticing it :)

On Monday, 28 December 2015, Luca Bonavita notifications@github.com wrote:

> Since you're using .require(readControllers('./src/js/controllers')) in
> gulpfile.js then maybe src/js/controller-bootstrap.js isn't needed?
> 
> Thanks a lot for publishing this solution!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rachel-carvalho/chaplin-browserify-gulp/issues/1.

## 

Rachel Carvalho

http://about.me/rachel.carvalho

**Comment by rachel-carvalho** [comment]
You were right, the file probably remained there from the first tests I was doing.
